-- MySQL Script generated by MySQL Workbench
-- Чт 29 окт 2020 02:35:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `id_area` INT NOT NULL,
  `name_area` VARCHAR(64) NOT NULL COMMENT 'Наименование области',
  `okrug_area` VARCHAR(64) NOT NULL COMMENT 'Название округа в который входит данный регион',
  `capital_area` INT NOT NULL COMMENT 'Областной центр, ссылка на таблицу city',
  `country_area` CHAR(2) NOT NULL COMMENT '2-х символьный код страны ссылка',
  PRIMARY KEY (`id_area`),
  UNIQUE INDEX `country_area_UNIQUE` (`country_area` ASC) VISIBLE,
  INDEX `fk_area_capital_idx` (`capital_area` ASC) VISIBLE,
  CONSTRAINT `fk_area_capital`
    FOREIGN KEY (`capital_area`)
    REFERENCES `mydb`.`сity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_area_country`
    FOREIGN KEY (`country_area`)
    REFERENCES `mydb`.`country` (`kod2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `name` VARCHAR(64) NOT NULL COMMENT 'Наименование сокращенное страны',
  `fullname` VARCHAR(64) NOT NULL COMMENT 'Наименование полное страны',
  `kod3` CHAR(3) NOT NULL COMMENT '3-х символьный код страны',
  `capital` INT NOT NULL COMMENT 'Код города - столицы страны, ссылка на таблицу city',
  `kod2` CHAR(2) NOT NULL,
  UNIQUE INDEX `kod2_UNIQUE` (`kod2` ASC) VISIBLE,
  INDEX `fk_country_capcity_idx` (`capital` ASC) VISIBLE,
  CONSTRAINT `fk_country_capcity`
    FOREIGN KEY (`capital`)
    REFERENCES `mydb`.`сity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `id_rgn` INT NOT NULL,
  `country_rgn` CHAR(2) NOT NULL,
  `capital_rgn` INT NOT NULL,
  PRIMARY KEY (`id_rgn`),
  UNIQUE INDEX `capital_rgn_UNIQUE` (`capital_rgn` ASC) VISIBLE,
  UNIQUE INDEX `country_rgn_UNIQUE` (`country_rgn` ASC) VISIBLE,
  CONSTRAINT `fk_region_country`
    FOREIGN KEY (`country_rgn`)
    REFERENCES `mydb`.`country` (`kod2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region_city` (
  `id_rgnc` INT NOT NULL,
  `name_rgnc` VARCHAR(128) NOT NULL,
  `citycode_rgnc` INT NOT NULL DEFAULT 0,
  `parent_region_rgnc` INT NOT NULL,
  PRIMARY KEY (`id_rgnc`),
  UNIQUE INDEX `citycode_rgnc_UNIQUE` (`citycode_rgnc` ASC) VISIBLE,
  UNIQUE INDEX `id_rgnc_UNIQUE` (`id_rgnc` ASC) VISIBLE,
  UNIQUE INDEX `parent_region_UNIQUE` (`parent_region_rgnc` ASC) VISIBLE,
  CONSTRAINT `fk_region_city_cc`
    FOREIGN KEY (`citycode_rgnc`)
    REFERENCES `mydb`.`сity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_region_city_rc`
    FOREIGN KEY (`parent_region_rgnc`)
    REFERENCES `mydb`.`region` (`id_rgn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`сity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`сity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `area` INT NOT NULL,
  `postcode` VARCHAR(255) NOT NULL DEFAULT 0 COMMENT 'Почтовый код',
  `level` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '1-Областной центр или город с населением более 1 млн.человек,\n2-Районный центр или город с населением более 100 тыс.человек,\n3-Город с населением более 15тыс.человек,\n4-Деревня/станица/хутор/аул и тд с населением менее 15тыс.человек',
  `country` CHAR(2) NOT NULL COMMENT '2 - символьный код страны',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `country_UNIQUE` (`country` ASC) VISIBLE,
  INDEX `fk_сity_area_idx` (`area` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_сity_country`
    FOREIGN KEY (`country`)
    REFERENCES `mydb`.`country` (`kod2`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_сity_area`
    FOREIGN KEY (`area`)
    REFERENCES `mydb`.`area` (`id_area`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
